name: Publish The Library

on:
  push:
    branches:
      - main

permissions:
  # https://stackoverflow.com/a/72183279/8784518
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check the current published version
        run: |
          LAST_PUBLISHED_VERSION=$(npm view nestjs-backend-common version 2> /dev/null || echo "")
          PACKAGE_VERSION=$(cat package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')
          [[ $LAST_PUBLISHED_VERSION == $PACKAGE_VERSION ]] && exit 1

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: "https://registry.npmjs.org/"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Apply Eslint
        run: pnpm lint

      - name: Run Unit Tests
        run: pnpm test:unit

      - name: Publish Package on npm 📦
        run: pnpm publish --provenance --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
